### ISSUE TITLE
Setup Unit Testing and Tests

### ISSUE THREAD

**Issue by adamlofting** [adamlofting/react-ga#3]

**Comment by toolness** [comment]
I'm happy to submit a PR for this if you like, just don't want to duplicate work if you're already on it!

**Comment by adamlofting** [comment]
I would absolutely love that. 

I've look at testing a few times, and always get confused by which frameworks to use. If we can do this in a way that is similar to MoFo projects going forward that would be even more helpful to me.

**Comment by toolness** [comment]
This is now superseded by #6!
